### ISSUE TITLE
attachable property not supported in network definition

### ISSUE THREAD

**Issue by raarts** [aanand/compose-file#35]
Is this the official parser for the compose v3 file as used by docker? In `docker-compose 1.10 rc2` all networks created by docker-compose are attachable. `docker deploy` though does not do this and does not recognise the attachable property.

**Comment by dnephin** [comment]
This library was imported into the `docker/docker` repo at `cli/compose/`.

I'd suggest opening an issue on `docker/docker`, as this behaviour is part of the client, not the config parsing. Please cc me if you open an issue there.

**Comment by raarts** [comment]
Here it is: docker/docker#30191
